# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmodel.proto\"\x1d\n\x05Input\x12\x14\n\x0cinput_smiles\x18\x01 \x01(\t\"w\n\nPrediction\x12\x17\n\x0fpredicted_class\x18\x01 \x01(\x02\x12\x1d\n\x15withdrawn_probability\x18\x02 \x01(\x02\x12\x17\n\x0fpvalue_approved\x18\x03 \x01(\x02\x12\x18\n\x10pvalue_withdrawn\x18\x04 \x01(\x02\"\x9a\x03\n\x12\x43omplementaryModel\x12R\n\x18\x63omplementary_prediction\x18\x01 \x03(\x0b\x32\x30.ComplementaryModel.ComplementaryPredictionEntry\x12H\n\x13\x63omplementary_tasks\x18\x02 \x03(\x0b\x32+.ComplementaryModel.ComplementaryTasksEntry\x12\x38\n\x0bshap_values\x18\x03 \x03(\x0b\x32#.ComplementaryModel.ShapValuesEntry\x1a>\n\x1c\x43omplementaryPredictionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x39\n\x17\x43omplementaryTasksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x31\n\x0fShapValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"/\n\x11\x46\x65\x61tureImportance\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"\xa7\x01\n\x0eGNNExplanation\x12\x17\n\x0f\x62ond_importance\x18\x01 \x01(\t\x12\x42\n\x12\x66\x65\x61ture_importance\x18\x02 \x03(\x0b\x32&.GNNExplanation.FeatureImportanceEntry\x1a\x38\n\x16\x46\x65\x61tureImportanceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\x81\x01\n\x07Predict\x12\x1e\n\x07predict\x12\x06.Input\x1a\x0b.Prediction\x12\x32\n\x13\x63omplementary_model\x12\x06.Input\x1a\x13.ComplementaryModel\x12\"\n\x07\x65xplain\x12\x06.Input\x1a\x0f.GNNExplanationb\x06proto3'
)




_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_smiles', full_name='Input.input_smiles', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=44,
)


_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predicted_class', full_name='Prediction.predicted_class', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='withdrawn_probability', full_name='Prediction.withdrawn_probability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pvalue_approved', full_name='Prediction.pvalue_approved', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pvalue_withdrawn', full_name='Prediction.pvalue_withdrawn', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=165,
)


_COMPLEMENTARYMODEL_COMPLEMENTARYPREDICTIONENTRY = _descriptor.Descriptor(
  name='ComplementaryPredictionEntry',
  full_name='ComplementaryModel.ComplementaryPredictionEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ComplementaryModel.ComplementaryPredictionEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ComplementaryModel.ComplementaryPredictionEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=468,
)

_COMPLEMENTARYMODEL_COMPLEMENTARYTASKSENTRY = _descriptor.Descriptor(
  name='ComplementaryTasksEntry',
  full_name='ComplementaryModel.ComplementaryTasksEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ComplementaryModel.ComplementaryTasksEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ComplementaryModel.ComplementaryTasksEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=527,
)

_COMPLEMENTARYMODEL_SHAPVALUESENTRY = _descriptor.Descriptor(
  name='ShapValuesEntry',
  full_name='ComplementaryModel.ShapValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ComplementaryModel.ShapValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ComplementaryModel.ShapValuesEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=578,
)

_COMPLEMENTARYMODEL = _descriptor.Descriptor(
  name='ComplementaryModel',
  full_name='ComplementaryModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='complementary_prediction', full_name='ComplementaryModel.complementary_prediction', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='complementary_tasks', full_name='ComplementaryModel.complementary_tasks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shap_values', full_name='ComplementaryModel.shap_values', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_COMPLEMENTARYMODEL_COMPLEMENTARYPREDICTIONENTRY, _COMPLEMENTARYMODEL_COMPLEMENTARYTASKSENTRY, _COMPLEMENTARYMODEL_SHAPVALUESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=578,
)


_FEATUREIMPORTANCE = _descriptor.Descriptor(
  name='FeatureImportance',
  full_name='FeatureImportance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='FeatureImportance.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='FeatureImportance.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=627,
)


_GNNEXPLANATION_FEATUREIMPORTANCEENTRY = _descriptor.Descriptor(
  name='FeatureImportanceEntry',
  full_name='GNNExplanation.FeatureImportanceEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GNNExplanation.FeatureImportanceEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='GNNExplanation.FeatureImportanceEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=741,
  serialized_end=797,
)

_GNNEXPLANATION = _descriptor.Descriptor(
  name='GNNExplanation',
  full_name='GNNExplanation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bond_importance', full_name='GNNExplanation.bond_importance', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_importance', full_name='GNNExplanation.feature_importance', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GNNEXPLANATION_FEATUREIMPORTANCEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=797,
)

_COMPLEMENTARYMODEL_COMPLEMENTARYPREDICTIONENTRY.containing_type = _COMPLEMENTARYMODEL
_COMPLEMENTARYMODEL_COMPLEMENTARYTASKSENTRY.containing_type = _COMPLEMENTARYMODEL
_COMPLEMENTARYMODEL_SHAPVALUESENTRY.containing_type = _COMPLEMENTARYMODEL
_COMPLEMENTARYMODEL.fields_by_name['complementary_prediction'].message_type = _COMPLEMENTARYMODEL_COMPLEMENTARYPREDICTIONENTRY
_COMPLEMENTARYMODEL.fields_by_name['complementary_tasks'].message_type = _COMPLEMENTARYMODEL_COMPLEMENTARYTASKSENTRY
_COMPLEMENTARYMODEL.fields_by_name['shap_values'].message_type = _COMPLEMENTARYMODEL_SHAPVALUESENTRY
_GNNEXPLANATION_FEATUREIMPORTANCEENTRY.containing_type = _GNNEXPLANATION
_GNNEXPLANATION.fields_by_name['feature_importance'].message_type = _GNNEXPLANATION_FEATUREIMPORTANCEENTRY
DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['Prediction'] = _PREDICTION
DESCRIPTOR.message_types_by_name['ComplementaryModel'] = _COMPLEMENTARYMODEL
DESCRIPTOR.message_types_by_name['FeatureImportance'] = _FEATUREIMPORTANCE
DESCRIPTOR.message_types_by_name['GNNExplanation'] = _GNNEXPLANATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:Input)
  })
_sym_db.RegisterMessage(Input)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTION,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:Prediction)
  })
_sym_db.RegisterMessage(Prediction)

ComplementaryModel = _reflection.GeneratedProtocolMessageType('ComplementaryModel', (_message.Message,), {

  'ComplementaryPredictionEntry' : _reflection.GeneratedProtocolMessageType('ComplementaryPredictionEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMPLEMENTARYMODEL_COMPLEMENTARYPREDICTIONENTRY,
    '__module__' : 'model_pb2'
    # @@protoc_insertion_point(class_scope:ComplementaryModel.ComplementaryPredictionEntry)
    })
  ,

  'ComplementaryTasksEntry' : _reflection.GeneratedProtocolMessageType('ComplementaryTasksEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMPLEMENTARYMODEL_COMPLEMENTARYTASKSENTRY,
    '__module__' : 'model_pb2'
    # @@protoc_insertion_point(class_scope:ComplementaryModel.ComplementaryTasksEntry)
    })
  ,

  'ShapValuesEntry' : _reflection.GeneratedProtocolMessageType('ShapValuesEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMPLEMENTARYMODEL_SHAPVALUESENTRY,
    '__module__' : 'model_pb2'
    # @@protoc_insertion_point(class_scope:ComplementaryModel.ShapValuesEntry)
    })
  ,
  'DESCRIPTOR' : _COMPLEMENTARYMODEL,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:ComplementaryModel)
  })
_sym_db.RegisterMessage(ComplementaryModel)
_sym_db.RegisterMessage(ComplementaryModel.ComplementaryPredictionEntry)
_sym_db.RegisterMessage(ComplementaryModel.ComplementaryTasksEntry)
_sym_db.RegisterMessage(ComplementaryModel.ShapValuesEntry)

FeatureImportance = _reflection.GeneratedProtocolMessageType('FeatureImportance', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREIMPORTANCE,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:FeatureImportance)
  })
_sym_db.RegisterMessage(FeatureImportance)

GNNExplanation = _reflection.GeneratedProtocolMessageType('GNNExplanation', (_message.Message,), {

  'FeatureImportanceEntry' : _reflection.GeneratedProtocolMessageType('FeatureImportanceEntry', (_message.Message,), {
    'DESCRIPTOR' : _GNNEXPLANATION_FEATUREIMPORTANCEENTRY,
    '__module__' : 'model_pb2'
    # @@protoc_insertion_point(class_scope:GNNExplanation.FeatureImportanceEntry)
    })
  ,
  'DESCRIPTOR' : _GNNEXPLANATION,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:GNNExplanation)
  })
_sym_db.RegisterMessage(GNNExplanation)
_sym_db.RegisterMessage(GNNExplanation.FeatureImportanceEntry)


_COMPLEMENTARYMODEL_COMPLEMENTARYPREDICTIONENTRY._options = None
_COMPLEMENTARYMODEL_COMPLEMENTARYTASKSENTRY._options = None
_COMPLEMENTARYMODEL_SHAPVALUESENTRY._options = None
_GNNEXPLANATION_FEATUREIMPORTANCEENTRY._options = None

_PREDICT = _descriptor.ServiceDescriptor(
  name='Predict',
  full_name='Predict',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=800,
  serialized_end=929,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='Predict.predict',
    index=0,
    containing_service=None,
    input_type=_INPUT,
    output_type=_PREDICTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='complementary_model',
    full_name='Predict.complementary_model',
    index=1,
    containing_service=None,
    input_type=_INPUT,
    output_type=_COMPLEMENTARYMODEL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='explain',
    full_name='Predict.explain',
    index=2,
    containing_service=None,
    input_type=_INPUT,
    output_type=_GNNEXPLANATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICT)

DESCRIPTOR.services_by_name['Predict'] = _PREDICT

# @@protoc_insertion_point(module_scope)
